version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_arena
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: arenapernambuco
    ports:
      - '3306:3306'

