<<<<<<< HEAD
spring.application.name=arenapernambuco

<<<<<<< HEAD
spring.datasource.url=jdbc:h2:mem:arenadb;DB_CLOSE_DELAY=-1
=======
spring.datasource.url=jdbc:h2:mem:testdb
>>>>>>> 2dca80b (Cadastro)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
<<<<<<< HEAD

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.security.frame-options=disable
=======
spring.datasource.url=jdbc:mysql://localhost:3306/arena_pernambuco?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
>>>>>>> 021efe57436934dc59377bea1290920604152e63
=======
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
>>>>>>> 2dca80b (Cadastro)
